# note deis builder (https://github.com/deis/builder) runs one deis-dockerbuilder pod per build,
# so it doesn't use this manifest
apiVersion: v1
kind: Service
metadata:
  # Give this a useful name.
  name: deis-dockerbuilder
  labels:
    heritage: deis
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
  selector:
    # Match the selector in the RC
    app: deis-dockerbuilder
